version: 2.1
orbs:
  node: circleci/node@2.0.1
  coveralls: coveralls/coveralls@1.0.4
jobs:
  build-and-test:
    executor:
      name: node/default
      tag: "12.18.0"
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y tzdata
      - run: sudo ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
      - checkout
      - run: yarn
      - run: yarn test-ci
      - coveralls/upload:
          path_to_lcov: "./reports/coverage/lcov.info"
      - store_test_results:
          path: test-results
  build-and-test-and-send-to-stryker:
    executor:
      name: node/default
      tag: "12.18.0"
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y tzdata
      - run: sudo ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
      - checkout
      - run: yarn
      - run: yarn test-ci
      - run: yarn stryker-mutate --reporters dashboard --dashboard.version $CIRCLE_BRANCH
      - coveralls/upload:
          path_to_lcov: "./reports/coverage/lcov.info"
      - store_test_results:
          path: test-results
workflows:
  build-and-test:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: /^(?!master).*$/
      - build-and-test-and-send-to-stryker:
          filters:
            branches:
              ignore: /^master/
